### ISSUE TITLE
Use configured host name for simulator instructions/documentation

### ISSUE THREAD

**Issue by mmmries** [mmmries/roombots#12]
On the simulation page the instructions say to connect to `ws://roombots.riesd.com` this should be changed to point to the currently configured hostname

**Comment by newellista** [comment]
Dang!  I was just about to open a PR!

**Comment by mmmries** [comment]
Sorry for the duplicated effort @newellista. I thought you would be busy with bluetooth and solar panels on a Saturday :sunny: :sunglasses:
