### ISSUE TITLE
Sensor Diagram on Docs Page

### ISSUE THREAD

**Issue by mmmries** [mmmries/roombots#13]
Every time we do an event I get questions about the orientation of the sensors on the roombot. I should just make a diagram of this and put it on the docs page.

**Comment by mmmries** [comment]
Here is a rough sketch of the sensors

<img width="851" alt="screen shot 2016-02-27 at 2 03 26 pm" src="https://cloud.githubusercontent.com/assets/80008/13375379/e818612e-dd5a-11e5-9b07-da1d446dee11.png">

The physical bumpers (`bumper_left` and `bumper_right`) are built into the physical roomba and take up nearly 45 degrees along the front edge of the roomba.

The light bumpers are infrared detectors which can "see" obstacles at a distance up to 3 inches ahead. I didn't measure the exact degrees from center, but the diagram is pretty close.

**Comment by lukeschunk** [comment]
Which one is the 'docs page'?
